- hosts: debian-8 , debian-9 , ubuntu-12 , ubuntu-14 , ubuntu-16 , ubuntu-18
  become: no
  tasks:
    - name: Install sources.list
      copy: src=sources.list-8_jessie dest=/etc/apt/sources.list mode=0644 owner=root group=root

    - name: Check for updates
      apt: 
        update_cache: yes
        cache_valid_time: 3600

    - name: Instal latest debian-archive-keyring
      apt:
        name: debian-archive-keyring
        state: latest

    - name: Install sudo via apt
      apt:
        name: sudo
        state: present
